/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CursoController;
import controlador.EstudianteController;
import controlador.NotasController;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import modelo.Curso;
import modelo.Estudiante;
import modelo.Validacion;

public class AgregarNotasEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form AgregarNotasEstudiante
     */
    NotasController notaControl = new NotasController();
    Validacion validarNotas = new Validacion();
    CursoController cursoController = new CursoController();
    EstudianteController controladorEstudiante = new EstudianteController();

    public AgregarNotasEstudiante() {
        initComponents();
//carga los cursos en la lista
        try {
            cursoController.listarCursos(listaCurso);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar los cursos del archivo");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregarNota = new javax.swing.JButton();
        lblNotaPromedio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonReverso = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        inputNota1 = new javax.swing.JTextField();
        inputNota2 = new javax.swing.JTextField();
        inputNota3 = new javax.swing.JTextField();
        listaCurso = new javax.swing.JComboBox<>();
        listaEstudiante = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(900, 570));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 570));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarNota.setBackground(new java.awt.Color(51, 255, 51));
        btnAgregarNota.setText("Agregar nota");
        btnAgregarNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarNotaMouseClicked(evt);
            }
        });
        btnAgregarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 177, 55));

        lblNotaPromedio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNotaPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotaPromedio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNotaPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 330, 20));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setText("Primer Nota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 130, 122, 33));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("Segunda Nota");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 211, -1, 34));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setText("Tercer Nota");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 278, 122, 34));

        jLabel5.setText("Estudiantes: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jButtonReverso.setBackground(new java.awt.Color(255, 0, 0));
        jButtonReverso.setText("Atras");
        jButtonReverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReversoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        jLabel6.setText("Cursos: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        inputNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNota1ActionPerformed(evt);
            }
        });
        inputNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNota1KeyTyped(evt);
            }
        });
        jPanel1.add(inputNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 130, 116, 33));

        inputNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNota2KeyTyped(evt);
            }
        });
        jPanel1.add(inputNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 211, 116, 33));

        inputNota3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNota3KeyTyped(evt);
            }
        });
        jPanel1.add(inputNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 278, 116, 33));

        listaCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaCursoItemStateChanged(evt);
            }
        });
        listaCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCursoMouseClicked(evt);
            }
        });
        jPanel1.add(listaCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 50, 170, -1));

        listaEstudiante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaEstudianteItemStateChanged(evt);
            }
        });
        jPanel1.add(listaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 330, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oleg-laptev-7jQh3EiS8Bs-unsplash.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void disablePasteAction(JComponent[] components) {

        for (JComponent campo : components) {
            InputMap map = campo.getInputMap();
            map.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
            map.put(KeyStroke.getKeyStroke(KeyEvent.VK_INSERT, Event.SHIFT_MASK), "null");
        }

    }
    private void btnAgregarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaActionPerformed

        String notaUno = inputNota1.getText();
        String notaDos = inputNota2.getText();
        String notaTres = inputNota3.getText();
//validamos que las notas sean numericas
        if (notaControl.VerificarDouble(notaUno, notaDos, notaTres)) {
//validamos que las notas esten en el rango
            if (!notaControl.validacionNotas(notaUno, notaDos, notaTres)) {
                JOptionPane.showMessageDialog(rootPane, "Algunos campos estan erroneos, la nota debe ir en un rango de 0 a 5");
            } else {

                Estudiante estudianteSeleccionado = (Estudiante) listaEstudiante.getSelectedItem();
                Curso cursoSeleccionado = (Curso) listaCurso.getSelectedItem();
//validamos que haya seleccionado un curso y un estudiante 
                if (estudianteSeleccionado == null || cursoSeleccionado == null) {
                    JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un curso y un estudiante");
                } else {

//sicumple todas las validaciones se crea la asignación
                    try {
                        notaControl.actualizarNota(cursoSeleccionado.getCodigo(), estudianteSeleccionado.getIdentificacion(), notaUno, notaDos, notaTres);
                        lblNotaPromedio.setText("Promedio actual: " + notaControl.CalcularNota(new ArrayList<>(Arrays.asList(Double.parseDouble(notaUno), Double.parseDouble(notaDos), Double.parseDouble(notaTres)))));
                        JOptionPane.showMessageDialog(rootPane, "Nota Actualizada");
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(rootPane, "Error al actualizar la nota en el archivo");
                    }

                }

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Por favor, llene los campos correctamente");
        }
    }//GEN-LAST:event_btnAgregarNotaActionPerformed

    private void inputNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNota1ActionPerformed

//validacion que evita los caracteres invalidos
    private void inputNota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNota1KeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != '.'))
            evt.consume();
    }//GEN-LAST:event_inputNota1KeyTyped

    private void inputNota2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNota2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != '.'))
            evt.consume();
    }//GEN-LAST:event_inputNota2KeyTyped

    private void inputNota3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNota3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != '.'))
            evt.consume();
    }//GEN-LAST:event_inputNota3KeyTyped

    private void listaCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaCursoItemStateChanged
//actualiza la lista de estudiantes dependiendo del curso seleccionado
        notaControl.camposVacios(inputNota1, inputNota2, inputNota3, lblNotaPromedio);
        try {
            Curso cursoSeleccionado = (Curso) listaCurso.getSelectedItem();
            controladorEstudiante.listaEstudianteCurso(listaEstudiante, cursoSeleccionado.getCodigo());

        } catch (IOException e) {
            System.out.println("Error en listar estudiantes");
        }

    }//GEN-LAST:event_listaCursoItemStateChanged

    private void listaEstudianteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaEstudianteItemStateChanged
//trae las notas del estudiante seleccionado en los campos
        lblNotaPromedio.setText("");
        Estudiante estudianteSeleccionado = (Estudiante) listaEstudiante.getSelectedItem();
        Curso cursoSeleccionado = (Curso) listaCurso.getSelectedItem();
        try {
            inputNota1.setText("" + notaControl.notaEstudiante(cursoSeleccionado.getCodigo(), estudianteSeleccionado.getIdentificacion()).get(0));
            inputNota2.setText("" + notaControl.notaEstudiante(cursoSeleccionado.getCodigo(), estudianteSeleccionado.getIdentificacion()).get(1));
            inputNota3.setText("" + notaControl.notaEstudiante(cursoSeleccionado.getCodigo(), estudianteSeleccionado.getIdentificacion()).get(2));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al obtener las notas del estudiante");
        }


    }//GEN-LAST:event_listaEstudianteItemStateChanged

    private void listaCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCursoMouseClicked

    }//GEN-LAST:event_listaCursoMouseClicked

    private void btnAgregarNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarNotaMouseClicked


    }//GEN-LAST:event_btnAgregarNotaMouseClicked

    private void jButtonReversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReversoActionPerformed
        //cierra la ventana actual y abre la correspondiente
        MenuProfesor menuProfe = new MenuProfesor();
        menuProfe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReversoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarNotasEstudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarNotasEstudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarNotasEstudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarNotasEstudiante.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNota;
    private javax.swing.JTextField inputNota1;
    private javax.swing.JTextField inputNota2;
    private javax.swing.JTextField inputNota3;
    private javax.swing.JButton jButtonReverso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNotaPromedio;
    private javax.swing.JComboBox<Curso> listaCurso;
    private javax.swing.JComboBox<Estudiante> listaEstudiante;
    // End of variables declaration//GEN-END:variables
}
