/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CursoController;
import controlador.EstudianteController;
import controlador.EstudianteCursoController;
import java.io.IOException;
import javax.swing.JOptionPane;
import modelo.Curso;
import modelo.Estudiante;

/**
 *
 * @author Sebastian Rosero
 */
public class AsignarEstudiante extends javax.swing.JFrame {

    EstudianteController controladorEstudiante = new EstudianteController();
    CursoController controlCurso = new CursoController();
    EstudianteCursoController controladorEstudianteCurso = new EstudianteCursoController();

    public AsignarEstudiante() {
        initComponents();

//se cargan los cursos y estudiantes en una lista
        try {
            controladorEstudiante.listaEstudiante(listaEstudiantes);
            controlCurso.listarCursos(listaCursos);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Error cargando los estudiantes o cursos del archivo");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listaEstudiantes = new javax.swing.JComboBox<>();
        listaCursos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonReverso = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(746, 317));
        setMinimumSize(new java.awt.Dimension(746, 317));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(746, 317));
        setResizable(false);
        setSize(new java.awt.Dimension(746, 317));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaEstudiantes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaEstudiantesItemStateChanged(evt);
            }
        });
        jPanel1.add(listaEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 159, 330, -1));

        jPanel1.add(listaCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 230, -1));

        jLabel5.setText("Cursos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel4.setText("Estudiantes: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButtonReverso.setBackground(new java.awt.Color(255, 0, 0));
        jButtonReverso.setText("Atras");
        jButtonReverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReversoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        btnAsignar.setBackground(new java.awt.Color(51, 255, 51));
        btnAsignar.setText("Asignar");
        btnAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarMouseClicked(evt);
            }
        });
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 88, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("ASIGNAR ESTUDIANTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oleg-laptev-7jQh3EiS8Bs-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void listaEstudiantesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaEstudiantesItemStateChanged


    }//GEN-LAST:event_listaEstudiantesItemStateChanged

    private void btnAsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarMouseClicked

        Curso curso = (Curso) listaCursos.getSelectedItem();
        Estudiante estudiante = (Estudiante) listaEstudiantes.getSelectedItem();
//se valida que haya seleccionado algo
        if (curso == null || estudiante == null) {
            JOptionPane.showMessageDialog(rootPane, "Debes Seleccionar un  curso y un estudiante");
        } else {
            try {
//si pasa las validaciones se crea la asignación
                controladorEstudianteCurso.crearEstudianteCurso(estudiante, curso);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(rootPane, "Error al asignar al estudiante");
            }
        }


    }//GEN-LAST:event_btnAsignarMouseClicked

    private void jButtonReversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReversoActionPerformed
        //cierra la ventana actual y abre la correspondiente
        MenuProfesor menuProfe= new MenuProfesor();
        menuProfe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReversoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton jButtonReverso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Curso> listaCursos;
    private javax.swing.JComboBox<Estudiante> listaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
