/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.InformeDetalladoController;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author PARZIVAL
 */
public class InformeDetalladoo extends javax.swing.JFrame {

    /**
     * Creates new form InformeGeneral
     */
    InformeDetalladoController controlInforme = new InformeDetalladoController();

    public InformeDetalladoo() {
        initComponents();
//actualiza la informacion de la tabla
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonReverso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(900, 570));
        setMinimumSize(new java.awt.Dimension(900, 570));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 570));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Nota 1", "Nota 2", "Nota 3", "Definitiva", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaInforme);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 890, 450));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("INFORME DETALLADO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jButtonReverso.setBackground(new java.awt.Color(255, 0, 0));
        jButtonReverso.setText("Atras");
        jButtonReverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReversoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReverso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 91, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oleg-laptev-7jQh3EiS8Bs-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReversoActionPerformed
        //cierra la ventana actual y abre la correspondiente
        MenuEstudiante menuEst = new MenuEstudiante();
        menuEst.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReversoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeDetalladoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeDetalladoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeDetalladoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeDetalladoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeDetalladoo().setVisible(true);
            }
        });
    }
//actualiza la informacion de la tabla

    private void actualizarTabla() {
        try {
            tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
                    controlInforme.CargarTabla(),
                    new String[]{
                        "Materia", "Nota 1", "Nota 2", "Nota 3", "Definitiva", "Descripción"
                    }
            ));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar la información del archivo");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReverso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaInforme;
    // End of variables declaration//GEN-END:variables
}
