/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.MenuController;
import controlador.UsuarioController;

/**
 *
 * @author PARZIVAL
 */
public class MenuEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form MenuEstudiante
     */
    MenuController controlador = new MenuController();

    public MenuEstudiante() {
        initComponents();
//Se inicializa la informacion del estudiante en los Labls
        lblNombre1.setText(UsuarioController.estudianteSesion.getNombre());
        lblApellido.setText(UsuarioController.estudianteSesion.getApellido());
        lblIdntificacion.setText(UsuarioController.estudianteSesion.getIdentificacion());
        lblUsuario.setText(UsuarioController.estudianteSesion.getUsuario());
        jLabelTitulo.setText("Bienvenido " + UsuarioController.estudianteSesion.getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblIdntificacion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonInformeGeneral = new javax.swing.JButton();
        jButtonInformeDetallado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(900, 570));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 570));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Usuario:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 101, 27));

        jLabel4.setText("Apellido:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 101, 27));

        lblnombre.setText("Nombre:");
        jPanel4.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 101, 27));
        jPanel4.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, 26));
        jPanel4.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 143, 28));
        jPanel4.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 136, 26));

        jLabel7.setText("Identificación:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 101, 27));
        jPanel4.add(lblIdntificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, 26));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-tipo-de-piel-del-cliente-7-100.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 480, 240));

        jButtonInformeGeneral.setBackground(new java.awt.Color(51, 255, 51));
        jButtonInformeGeneral.setText("Informe general");
        jButtonInformeGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInformeGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 170, 40));

        jButtonInformeDetallado.setBackground(new java.awt.Color(51, 255, 51));
        jButtonInformeDetallado.setText("Informe detallado");
        jButtonInformeDetallado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformeDetalladoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInformeDetallado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 180, 40));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unnamed (1).png"))); // NOI18N
        jLabel1.setText("Cerrar Sesion");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 42));

        jLabelTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 220, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/oleg-laptev-7jQh3EiS8Bs-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1020, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInformeDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeDetalladoActionPerformed
        //cierra la ventana actual y abre la correspondiente 
        InformeDetalladoo informeDetalle = new InformeDetalladoo();
        informeDetalle.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonInformeDetalladoActionPerformed

    private void jButtonInformeGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformeGeneralActionPerformed
        //cierra la ventana actual y abre la correspondiente 
        InformeGeneral informeGeneral = new InformeGeneral();
        informeGeneral.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonInformeGeneralActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
//cierra la ventana actual y abre la correspondiente         
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInformeDetallado;
    private javax.swing.JButton jButtonInformeGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblIdntificacion;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblnombre;
    // End of variables declaration//GEN-END:variables
}
